{
 "title": "Steptember",
 "time": { "from": "now/w", "to": "now" },
 "panels": [
  {
   "title": "Badly Estimated Team Calories Burnt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  `teams`.`name` as 'team_name', \n  `subquery`.`steps` as 'steps',\n  `subquery`.`time` as 'time'\nFROM teams, (\n    SELECT  \n      MAX(`participants`.`team_id`) as 'team_id',\n      SUM(`records`.`calories_burnt`) as 'steps', \n      MAX(`records`.`time`) as 'time'\n    FROM `records` \n    INNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id`\n    GROUP BY UNIX_TIMESTAMP(`records`.`time`) DIV 300, `participants`.`team_id`\n) subquery \nWHERE `teams`.`id` = `subquery`.`team_id` AND $__timeFilter(`subquery`.`time`)\nORDER BY `subquery`.`time` DESC"
    }
   ]
  },
  {
   "title": "Badly Estimated Participant Calories Burnt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n    `participants`.`name` as 'metric',\n    `records`.`calories_burnt` as 'value', \n    `records`.`time` as 'time'\nFROM `records` \nINNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id`\nWHERE $__timeFilter(`records`.`time`)\nORDER BY `records`.`time` DESC"
    }
   ]
  },
  {
   "title": "Team Steps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  `teams`.`name` as 'team_name', \n  `subquery`.`steps` as 'steps',\n  `subquery`.`time` as 'time'\nFROM teams, (\n    SELECT  \n      MAX(`participants`.`team_id`) as 'team_id',\n      SUM(`records`.`steps`) as 'steps', \n      MAX(`records`.`time`) as 'time'\n    FROM `records` \n    INNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id`\n    GROUP BY UNIX_TIMESTAMP(`records`.`time`) DIV 300, `participants`.`team_id`\n) subquery \nWHERE `teams`.`id` = `subquery`.`team_id` AND $__timeFilter(`subquery`.`time`)\nORDER BY `subquery`.`time` DESC"
    }
   ]
  },
  {
   "title": "Participant Steps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n    `participants`.`name` as 'metric',\n    `records`.`steps` as 'value', \n    `records`.`time` as 'time'\nFROM `records` \nINNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id`\nWHERE $__timeFilter(`records`.`time`)\nORDER BY `records`.`time` DESC"
    }
   ]
  },
  {
   "title": "Company Data",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(`subquery`.`distance`) / 1000 as 'distance',\n  SUM(`subquery`.`steps`) as 'steps',\n  SUM(`subquery`.`calories_burnt`) as 'calories_burnt'\nFROM (\n    SELECT\n      MAX(`records`.`participant_id`) as 'id',\n      MAX(`records`.`distance`) as 'distance',\n      MAX(`records`.`steps`) as 'steps',\n      MAX(`records`.`calories_burnt`) as 'calories_burnt'\n    FROM `records`\n    INNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id`\n    WHERE $__timeFilter(`records`.`time`)\n    GROUP BY `records`.`participant_id`\n) as subquery"
    }
   ]
  },
  {
   "title": "Participant Data",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  `participants`.`name`,\n  MAX(`records`.`distance`) / 1000 as 'distance',\n  MAX(`records`.`steps`) as 'steps',\n  MAX(`records`.`calories_burnt`) as 'calories_burnt',\n  MAX(`records`.`steps`) - MAX(`subquery`.`growth`) as 'growth'\nFROM `records`\nINNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id`\nLEFT JOIN (\n    SELECT\n      MAX(`records`.`steps`) as 'growth',\n      `records`.`participant_id` as 'participant_id'\n    FROM `records`\n      INNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id`\n      WHERE `records`.`time` >= FROM_UNIXTIME($__unixEpochFrom() - ($__unixEpochTo() - $__unixEpochFrom()))\n      AND `records`.`time` <= $__timeFrom()\n     GROUP BY `records`.`participant_id`\n) as subquery ON `records`.`participant_id`=`subquery`.`participant_id`\nWHERE $__timeFilter(`records`.`time`)\nGROUP BY `records`.`participant_id`"
    }
   ]
  },
  {
   "title": "Team Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n  `teams`.`name` as 'team_name', \n  SUM(`subquery`.`distance`) / 1000 as 'distance', \n  SUM(`subquery`.`steps`) as 'steps', \n  SUM(`subquery`.`calories_burnt`) as 'calories_burnt' \nFROM teams, (\n    SELECT \n      `participants`.`team_id` as 'team_id', \n      `participants`.`name`, \n      MAX(`records`.`distance`) as 'distance', \n      MAX(`records`.`steps`) as 'steps', \n      MAX(`records`.`calories_burnt`) as 'calories_burnt' \n    FROM `records` \n    INNER JOIN `participants` ON `records`.`participant_id`=`participants`.`id` \n    WHERE $__timeFilter(`records`.`time`)\n    GROUP BY `records`.`participant_id`\n) subquery \nWHERE `teams`.`id` = `subquery`.`team_id` \nGROUP BY `subquery`.`team_id`"
    }
   ]
  }
 ]
}